# Common
"0" = "نجاح"
"400" = "خطأ في المعامل"
"401" = "فشل المصادقة"
"403" = "لا يوجد إذن للوصول"
"404" = "المسار غير موجود"
"500" = "خطأ داخلي"

# Auth Service
"10001" = "كلمة المرور غير صحيحة، يُرجى إدخال كلمة المرور الصحيحة والمحاولة مرة أخرى."
"10002" = "محاولات كثيرة جدًا، يُرجى المحاولة لاحقًا."
"10003" = "لم يتم التحقق من البريد الإلكتروني."
"10004" = "الحساب مُعلّق."
"10005" = "الحساب غير موجود، يُرجى إدخال الحساب الصحيح والمحاولة مرة أخرى."
"10006" = "تم الوصول إلى حدّ السرعة، يُرجى المحاولة لاحقًا."
"10007" = "طلبات كثيرة جدًا، يُرجى المحاولة لاحقًا."
"10008" = "الحساب مُحظور مؤقتًا."
"10009" = "المستخدم مُقفل."
"10010" = "رمز غير صالح أو تنسيق غير صحيح."
"10011" = "انتهت صلاحية الرمز، يُرجى تحديث الرمز والمحاولة مرة أخرى."
"10012" = "الرمز غير موجود في الطلب."
"10013" = "سياق المستخدم غير موجود."
"10014" = "الشركة غير موجودة."
"10015" = "الدور غير موجود."

# Subscription Service
"15000" = "مُعرّف شركة غير صالح."
"15001" = "الاشتراك غير موجود."
"15002" = "اشتراك التطبيق غير موجود."

# Payment Service
"20000" = "سجل الرصيد غير موجود."
